---

- name: Apt update
  apt:
    update_cache: yes

- name: Install required software
  apt:
    name:
      - mariadb-server

- name: Update default Apache site
  lineinfile:
    dest=/etc/mysql/mariadb.conf.d/50-server.cnf
    regexp="bind-address            = 127.0.0.1"
    line="bind-address            = 0.0.0.0"

- name: Enabled mysql
  service:
    name: mysql
    state: started
    enabled: yes

- name: Cretate database
  command: mysql --user root --password="{{mysql_password}}" --execute="CREATE DATABASE wordpress DEFAULT CHARACTER SET utf8;"
  ignore_errors: yes

- debug:
    msg: 'Continue'

- name: Create user and Grant all
  command: mysql --user root --"{{mysql_password}}" --execute="GRANT ALL ON wordpress.* TO virl@'%' IDENTIFIED BY 'Cisco.virl777';"
  ignore_errors: yes

- debug:
    msg: 'Continue'
